name: PR liniting

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, edited, reopened]

jobs:
  verify-pr-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Pull Request Labels
      uses: jesusvasquez333/verify-pr-label-action@v1.1.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'ready-for-merge'
      if: github.event_name == 'pull_request' && contains(['opened', 'labeled', 'unlabeled', 'synchronize'], github.event.action)
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Pull Request Labels
      uses: morrisoncole/pr-lint-action@v1.1.0
      with:
        title-regex: "#VC-[0-9]+"
        on-failed-regex-comment: "This is just an example. Failed regex: `%regex%`!"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
      if: github.event_name == 'pull_request' && contains(['opened', 'edited', 'reopened'], github.event.action)
