name: PR liniting

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify-pr-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    #- name: Verify Pull Request Labels
    #  uses: jesusvasquez333/verify-pr-label-action@v1.1.0
    #  with:
    #    github-token: '${{ secrets.GITHUB_TOKEN }}'
    #    valid-labels: 'ready-for-merge'
