name: PR liniting
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Pull Request Labels
      uses: morrisoncole/pr-lint-action@v1.1.0
      with:
        title-regex: "#VC-[0-9]+"
        on-failed-regex-comment: "This is just an example. Failed regex: `%regex%`!"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
