name: Verify PR Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
jobs:
  verify-pr-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR has required labels
      env:
        READY_FOR_MERGE: ${{ contains(github.event.pull_request.labels.*.name, 'ready-for-merge') }}
        ALL_LABELS: ${{ toJson(github.event.pull_request.labels) }}
      run: |
       echo $ALL_LABELS
       test "${READY_FOR_MERGE}" == "true" || { echo "'ready-for-merge' label was not added to PR"; exit 1; } 
    - name: update-previous-checks
      uses: Logitech/vc-update-gh-actions@v1.0.0
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        check_name: verify-pr-labels
